spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo-db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: db/changelog/master-changelog.xml